dist: bionic

language: node_js
node_js:
  - lts/erbium
  - node

git:
  depth: 3

cache:
  yarn: true
  directories:
    - node_modules

branches:
  except:
    # do not build any branches that have *.tmp in their name
    - /.*\.tmp$/

addons:
  chrome: stable
